// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package cmd // import "github.com/telnet2/pm/pubsub"

import (
	"sync"
	"time"
)

var wgStringPool = sync.Pool{New: func() interface{} { return new(sync.WaitGroup) }}

// NewStringPublisher creates a new pub/sub publisher to broadcast messages.
// The duration is used as the send timeout as to not block the publisher publishing
// messages to other clients if one client is slow or unresponsive.
// The buffer is used when creating new channels for subscribers.
func NewStringPublisher(publishTimeout time.Duration, buffer int) *StringPublisher {
	return &StringPublisher{
		buffer:      buffer,
		timeout:     publishTimeout,
		subscribers: make(map[_StringSubscriber]_StringTopicFunc),
	}
}

type _StringSubscriber chan string
type _StringTopicFunc func(v string) bool

// StringPublisher is basic pub/sub structure. Allows to send events and subscribe
// to them. Can be safely used from multiple goroutines.
type StringPublisher struct {
	m           sync.RWMutex
	buffer      int
	timeout     time.Duration
	subscribers map[_StringSubscriber]_StringTopicFunc
}

// Len returns the number of subscribers for the publisher
func (p *StringPublisher) Len() int {
	p.m.RLock()
	i := len(p.subscribers)
	p.m.RUnlock()
	return i
}

// Subscribe adds a new subscriber to the publisher returning the channel.
func (p *StringPublisher) Subscribe() chan string {
	return p.SubscribeTopic(nil)
}

// SubscribeTopic adds a new subscriber that filters messages sent by a topic.
func (p *StringPublisher) SubscribeTopic(topic _StringTopicFunc) chan string {
	ch := make(chan string, p.buffer)
	p.m.Lock()
	p.subscribers[ch] = topic
	p.m.Unlock()
	return ch
}

// SubscribeTopicWithBuffer adds a new subscriber that filters messages sent by a topic.
// The returned channel has a buffer of the specified size.
func (p *StringPublisher) SubscribeTopicWithBuffer(topic _StringTopicFunc, buffer int) chan string {
	ch := make(chan string, buffer)
	p.m.Lock()
	p.subscribers[ch] = topic
	p.m.Unlock()
	return ch
}

// Evict removes the specified subscriber from receiving any more messages.
func (p *StringPublisher) Evict(sub chan string) {
	p.m.Lock()
	_, exists := p.subscribers[sub]
	if exists {
		delete(p.subscribers, sub)
		close(sub)
	}
	p.m.Unlock()
}

// Publish sends the data in v to all subscribers currently registered with the publisher.
func (p *StringPublisher) Publish(v string) {
	p.m.RLock()
	if len(p.subscribers) == 0 {
		p.m.RUnlock()
		return
	}

	wg := wgStringPool.Get().(*sync.WaitGroup)
	for sub, topic := range p.subscribers {
		wg.Add(1)
		go p.sendTopic(sub, topic, v, wg)
	}
	wg.Wait()
	wgStringPool.Put(wg)
	p.m.RUnlock()
}

// Close closes the channels to all subscribers registered with the publisher.
func (p *StringPublisher) Close() {
	p.m.Lock()
	for sub := range p.subscribers {
		delete(p.subscribers, sub)
		close(sub)
	}
	p.m.Unlock()
}

func (p *StringPublisher) sendTopic(sub _StringSubscriber, topic _StringTopicFunc, v string, wg *sync.WaitGroup) {
	defer wg.Done()
	if topic != nil && !topic(v) {
		return
	}

	// send under a select as to not block if the receiver is unavailable
	if p.timeout > 0 {
		timeout := time.NewTimer(p.timeout)
		defer timeout.Stop()

		select {
		case sub <- v:
		case <-timeout.C:
		}
		return
	}

	select {
	case sub <- v:
	default:
	}
}
